/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/d9I2FOcXou7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import React, { useCallback, useState }  from "react";
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {

  const [animationRequest, setAnimationRequest] = useState<string>("");
  const [videoUrl, setVideoUrl] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string>("");
  
  const handleGenerate = async () => {
    setIsLoading(true);
    setError("");
    setVideoUrl("");
    try {
      const generateResponse = await fetch(
        "http://localhost:3001/api/v1/generate-script",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ userPrompt: animationRequest }),
        }
      );

      if (!generateResponse.ok) {
        throw new Error("Failed to generate animation");
      }

      const getAnimationResponse = await fetch(
        "http://localhost:3001/api/v1/generate-script",
      )
      if (!getAnimationResponse.ok) {
        throw new Error("Failed to retrieve animation");
      }
    } catch(error) {
      
    }
  }

  return (
    <div className="flex flex-col items-center w-full min-h-screen p-4">
      <header className="flex justify-between w-full p-4 border-b">
        <div className="text-lg font-bold">Logo</div>
      </header>
      <main className="flex flex-col items-center w-full flex-1 p-4">
        <h1 className="text-2xl font-bold text-center mb-4">Do you know how to actually make math beautiful?</h1>
        <div className="flex flex-col items-center w-full max-w-lg space-y-4">
          <Input type="text" placeholder="Enter request for creating Manim animation" className="w-full" />
          <div className="flex flex-col gap-4 w-full">
            <Button className="flex-1">Generate</Button>
            <div className="flex gap-4 w-full">
              <Button variant="outline" className="flex-1">
                Animate Equations
              </Button>
              <Button variant="outline" className="flex-1">
                Visualize Concepts
              </Button>
              <Button variant="outline" className="flex-1">
                Explain Theorems
              </Button>
            </div>
          </div>
        </div>
        <div className="flex items-center justify-center w-full max-w-lg mt-8 border h-[200px]">Place for video</div>
        <div className="flex items-center justify-center w-full max-w-lg mt-8 border h-[200px]">Place for audio</div>
      </main>
    </div>
  )
}
